# Generated by Django 5.0.6 on 2024-06-24 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalesReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('sales', models.FloatField()),
                ('product', models.CharField(max_length=25)),
            ],
        ),
    ]
