# Generated by Django 5.0.6 on 2024-06-24 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chartitApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesreport',
            name='product',
        ),
    ]
